import prettier from "eslint-config-prettier";

export default [
  {
    files: ["js/**/*.js"],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "module",
      globals: {
        window: "readonly",
        document: "readonly",
        navigator: "readonly",
        console: "readonly",
        performance: "readonly",
        localStorage: "readonly",
        sessionStorage: "readonly",
        requestAnimationFrame: "readonly",
        cancelAnimationFrame: "readonly",
        setTimeout: "readonly",
        clearTimeout: "readonly",
        setInterval: "readonly",
        clearInterval: "readonly",
        fetch: "readonly",
        URL: "readonly",
        URLSearchParams: "readonly",
        Image: "readonly",
        Blob: "readonly",
        XMLSerializer: "readonly",
        HTMLAudioElement: "readonly",
        HTMLElement: "readonly",
        SVGElement: "readonly",
        ResizeObserver: "readonly",
        MutationObserver: "readonly",
        AudioContext: "readonly",
        Path2D: "readonly",
        Float32Array: "readonly",
        Uint8Array: "readonly",
        history: "readonly",
        location: "readonly",
        screen: "readonly",
        matchMedia: "readonly",
        confetti: "readonly",
      },
    },
    rules: {
      "no-unused-vars": ["warn", { argsIgnorePattern: "^_" }],
      "no-console": ["warn", { allow: ["warn", "error"] }],
      "prefer-const": "warn",
      "no-var": "error",
      eqeqeq: ["error", "always"],
    },
  },
  prettier,
];
